apiVersion: v1
entries:
  kjwikigdocker:
  - apiVersion: v1
    appVersion: 0.0.982
    created: "2025-12-24T16:09:51.5840079+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: ca59b2be0c9a3c923490d4c23317b28fa4e43a69c5281539cacdae0f034bc7e9
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.982.tgz
    version: 0.0.982
  - apiVersion: v1
    appVersion: 0.0.981
    created: "2025-12-24T16:09:51.5834773+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: afe324c6fc9c9b10d5d5866ef76c0bac950eb8a409df01a76f20c2ff38a36e40
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.981.tgz
    version: 0.0.981
  - apiVersion: v1
    appVersion: 0.0.980
    created: "2025-12-24T16:09:51.5726754+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 3cd21c939ce542707d195c04a7e98871d7c72ae5d640b9ca65b855fa30a1226d
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.980.tgz
    version: 0.0.980
  - apiVersion: v1
    appVersion: 0.0.979
    created: "2025-12-24T16:09:51.558383+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 3acc13189bedc1e075146c550f63eabe48d41e180eb4fbf5adc059fd84bca556
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.979.tgz
    version: 0.0.979
  - apiVersion: v1
    appVersion: 0.0.978
    created: "2025-12-24T16:09:51.5536547+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 1275c77d657c6a8b1a2e6f8d116e56a86d0bb2bf857bb325a6bbf7292dac4782
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.978.tgz
    version: 0.0.978
  - apiVersion: v1
    appVersion: 0.0.977
    created: "2025-12-24T16:09:51.5404146+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: f9b55cd72e31ec42b2006b78cb106c7c636a5014b9c34e4489a8a08763e8e2d2
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.977.tgz
    version: 0.0.977
  - apiVersion: v1
    appVersion: 0.0.976
    created: "2025-12-24T16:09:51.5302555+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: b08ab282adc3f9f20db11aac744c81508373f41676d75d881c9b90bb0f135c1a
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.976.tgz
    version: 0.0.976
  - apiVersion: v1
    appVersion: 0.0.975
    created: "2025-12-24T16:09:51.5194485+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: f9ad80ac919216d7be86ba3073136e27494f4c371f8403572be31e69026a99a9
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.975.tgz
    version: 0.0.975
  - apiVersion: v1
    appVersion: 0.0.974
    created: "2025-12-24T16:09:51.5184039+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: fa9e44dae6c91ddc813cc593b832ce74e2935277f4e1bea053eb2c1c9011615a
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.974.tgz
    version: 0.0.974
  - apiVersion: v1
    appVersion: 0.0.973
    created: "2025-12-24T16:09:51.5009117+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 01600d56e888c5df141b72c226eef25c7d583c1df83eba936503626a56a94332
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.973.tgz
    version: 0.0.973
  - apiVersion: v1
    appVersion: 0.0.972
    created: "2025-12-24T16:09:51.4841877+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 68ebf5f132e41d704ceaaefebdeaad94bcf050a03a7162ac75bc0de7c2ab78db
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.972.tgz
    version: 0.0.972
  - apiVersion: v1
    appVersion: 0.0.971
    created: "2025-12-24T16:09:51.4760915+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 507110bebc97a4705ba6ffc6d7063dfabdbb2e70b5231dd88b222fc74b1a1bcf
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.971.tgz
    version: 0.0.971
  - apiVersion: v1
    appVersion: 0.0.970
    created: "2025-12-24T16:09:51.4676181+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 790b4172f8c3e794fc2420e622132ec0a324f0bdab4f61d29c97b71f2824d98b
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.970.tgz
    version: 0.0.970
  - apiVersion: v1
    appVersion: 0.0.969
    created: "2025-12-24T16:09:51.4571237+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 84094741fd0ec062fa6ebcac40c7bf78b5a6257f2101a6a3acc5c1df3ff470b1
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.969.tgz
    version: 0.0.969
  - apiVersion: v1
    appVersion: 0.0.968
    created: "2025-12-24T16:09:51.4561169+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 01fb1dd6128538117c133e819c1523b100e5098fc6ee86e2218876aa418adb38
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.968.tgz
    version: 0.0.968
  - apiVersion: v1
    appVersion: 0.0.967
    created: "2025-12-24T16:09:51.4458272+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 3ec9d3831cc1148ae90113e7c69c859d2f0d05d58bf58799eb2b35cee244a624
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.967.tgz
    version: 0.0.967
  - apiVersion: v1
    appVersion: 0.0.966
    created: "2025-12-24T16:09:51.4343197+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: ad352885f445b185862b821b955fd34837dc7cbd4c6985463ba35f37a003a62f
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.966.tgz
    version: 0.0.966
  - apiVersion: v1
    appVersion: 0.0.965
    created: "2025-12-24T16:09:51.4254678+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: b19f10c076db1b5591c3cf3153b4f850d62ca58c657ac27f6cb7758e9749ea49
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.965.tgz
    version: 0.0.965
  - apiVersion: v1
    appVersion: 0.0.964
    created: "2025-12-24T16:09:51.4078549+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: b10d5d14102718972bc97be4494748ddbda786866d19d526153d7673651edc8c
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.964.tgz
    version: 0.0.964
  - apiVersion: v1
    appVersion: 0.0.963
    created: "2025-12-24T16:09:51.395965+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: b0609d7c89075eb4e7dc2e2cb43e94d540137c864f2bc0c14c97fc9f48790f4a
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.963.tgz
    version: 0.0.963
  - apiVersion: v1
    appVersion: 0.0.962
    created: "2025-12-24T16:09:51.3949062+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: f3be67f3def8c9af26db008245f10ee2afee7956a07d3c11dea6ce40d5cde3a3
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.962.tgz
    version: 0.0.962
  - apiVersion: v1
    appVersion: 0.0.961
    created: "2025-12-24T16:09:51.3902113+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 38366cc020a12c18745b6c81cd5a9700a3fddd558fc871045f424069380523d2
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.961.tgz
    version: 0.0.961
  - apiVersion: v1
    appVersion: 0.0.960
    created: "2025-12-24T16:09:51.385022+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 6d4822b74b4a1df2ccb96c4b638a45359b9a4d0cb99f0308dbdbbe3300c7ca14
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.960.tgz
    version: 0.0.960
  - apiVersion: v1
    appVersion: 0.0.958
    created: "2025-12-24T16:09:51.3659628+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 9772d74f7e6416138cbcc92ac2feb7ff7d723645752726858d06ad6a918c71cf
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.958.tgz
    version: 0.0.958
  - apiVersion: v1
    appVersion: 0.0.957
    created: "2025-12-24T16:09:51.3593632+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 3070755db3d88430e3a6080fec9ddd3fac93f90d9b696c9a576429918384210b
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.957.tgz
    version: 0.0.957
  - apiVersion: v1
    appVersion: 0.0.956
    created: "2025-12-24T16:09:51.3451717+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 25a5f51c7c583a0f8c84edc11ea146f92d799e9609494870f2040208e5630d4c
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.956.tgz
    version: 0.0.956
  - apiVersion: v1
    appVersion: 0.0.955
    created: "2025-12-24T16:09:51.3321778+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 0cbb475449e4171cc5014d90c63f624ae17df87c299648d11cb1d730239cb9e0
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.955.tgz
    version: 0.0.955
  - apiVersion: v1
    appVersion: 0.0.954
    created: "2025-12-24T16:09:51.3138198+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 122a4fb1a8dd8bdbc87a09e842731234155212d95d2cc21418167fd0bcec8829
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.954.tgz
    version: 0.0.954
  - apiVersion: v1
    appVersion: 0.0.953
    created: "2025-12-24T16:09:51.3059744+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: 77937b8e43223ca1e5d1c636e8b76aad23b95c8cb5bd7c20f2396f1eeac4a97d
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.953.tgz
    version: 0.0.953
  - apiVersion: v1
    appVersion: 0.0.952
    created: "2025-12-24T16:09:51.2932939+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: dfe214a630228d9c52460c606855f496a380e62d1cb39f10bb9f23347b34d324
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.952.tgz
    version: 0.0.952
  - apiVersion: v1
    appVersion: 0.0.951
    created: "2025-12-24T16:09:51.2828276+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: b43b209368de9979a8d4d5c63688863f6f0eb5eba2d6ba752df66c5171ce8996
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.951.tgz
    version: 0.0.951
  - apiVersion: v1
    appVersion: 0.0.950
    created: "2025-12-24T16:09:51.2668002+09:00"
    description: wiki on Tomcat 10.1 , data files stores into PVC
    digest: c07671116a62070c6b87be9fdd2760e71f5912cdc172b1207d417b45f3593fa8
    keywords:
    - wiki
    name: kjwikigdocker
    urls:
    - https://raw.githubusercontent.com/george-pon/kjwikigdocker/master/helm-chart/charts/kjwikigdocker-0.0.950.tgz
    version: 0.0.950
generated: "2025-12-24T16:09:51.2354354+09:00"
